version: '3'
services:
  sinatra-basic-app:
    build: ./sinatra-basic-app
    volumes:
      - ./sinatra-basic-app:/code
      - sba_local_bundle:/usr/local/bundle
    ports:
      - "4567:4567"
    command: bundle exec ruby app.rb -o 0.0.0.0

volumes:
    sba_local_bundle: {}
